name: Python application

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-prefect-workflows:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Authenticate with Prefect Cloud
        env: 
          PREFECT_API_KEY: ${{ secrets.PREFECT_API_KEY }}
          WORKSPACE_KEY: ${{ secrets.WORKSPACE_KEY }}
        run: |
          prefect cloud login --key $PREFECT_API_KEY --workspace 'bits-apidriven/default'

      - name: Run Prefect deployment on Prefect Cloud
        env: 
          WORKSPACE_KEY: ${{ secrets.WORKSPACE_KEY }}
        run: |
          prefect deployment run 'workflow_employee_attrition/employee-attrition-analysis-workflow'
    
